name: onair
channels:
  - default
  - conda-forge
dependencies:
  - python==3.11.*
  - numpy==1.23.4
  - coverage==6.5.0
  - pytest==7.2.0
  - pytest-mock==3.10.0
  - pytest-randomly==3.12.0
  - pip
  - pip:
    - redis==4.6.0