name: onair
channels:
  - conda-forge
  - nodefaults
exclude:
  - defaults
dependencies:
  - python>=3.8,<3.13
  - numpy
  - coverage
  - pytest
  - pytest-mock
  - pytest-randomly
  - pip
  - pip:
    - redis
