# GSC-19165-1, "The On-Board Artificial Intelligence Research (OnAIR) Platform"
#
# Copyright © 2023 United States Government as represented by the Administrator of
# the National Aeronautics and Space Administration. No copyright is claimed in the
# United States under Title 17, U.S. Code. All Other Rights Reserved.
#
# Licensed under the NASA Open Source Agreement version 1.3
# See "NOSA GSC-19165-1 OnAIR.pdf"

from datetime import datetime
from onair.src.ai_components.ai_plugin_abstract.ai_plugin import AIPlugin

class Plugin(AIPlugin):
    def __init__(self, name, headers):
        super().__init__(name, headers)

        # Init some basic parameters, like number of entries for a single file
        self.first_frame = True
        self.lines_per_file = 10
        self.lines_current = 0
        self.current_buffer = [] # List of telemetry points
        self.filename_preamble = "csv_out_"
        self.filename = ""

        # Note: Files might exceede the specified lines_per_file if data is written too quickly.
        # File names are generated by a timestamp, so new files can only be created every minute at most.

    def update(self,low_level_data=[], high_level_data={}):
        """
        Given streamed data point, system should update internally
        """
        
        if (self.first_frame):
            # in each layer, find all plugins and append the name of the plugin to the headers
            for layer in high_level_data.keys():
                for plugin in high_level_data[layer]:
                    self.headers.append(str(plugin))

        self.current_buffer = []

        # Add low level data
        for telem_point in low_level_data:
            self.current_buffer.append(str(telem_point))

        # Add high level data
        for layer in high_level_data.keys():

            for plugin in high_level_data[layer]:
                plugin_output = high_level_data[layer].get(plugin, "empty")
                # Assume each plugin is outputting a list
                for telem_point in plugin_output:
                    self.current_buffer.append(str(telem_point))
                    
    def render_reasoning(self):
        """
        System should return its diagnosis
        """

        if (self.first_frame):
            date_stamp = datetime.today().strftime('%j_%H_%M')
            self.file_name = self.filename_preamble + date_stamp + ".csv"

            # Write out headers to file
            with open(self.file_name, 'a') as file:
                delimiter = ','
                file.write(delimiter.join(self.headers) + '\n')
            self.first_frame = False
        pass

        # Write out data frame to file
        with open(self.file_name, 'a') as file:
            delimiter = ','
            file.write(delimiter.join(self.current_buffer) + '\n')
        self.current_buffer = []
        self.lines_current += 1

        if (self.lines_per_file != 0 and self.lines_per_file == self.lines_current):
            # Create new file
            date_stamp = datetime.today().strftime('%j_%H_%M')
            self.file_name = self.filename_preamble + date_stamp + ".csv"

            self.lines_current = 0
